### ISSUE TITLE
Create Initial Release

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/cyclonedx-cocoapods#1]
Cocoapods itself is written in Ruby. It can be assumed that many of the dependencies used for analyzing the manifest are also written in Ruby. The CycloneDX implementation should also be written in Ruby so that it can take advantage of the native ecosystems ability to resolve dependencies. 

- Written in Ruby
- Include component name, version, hashes, purl, and optionally any additional information.

It may be possible to build on top of the work from https://github.com/CycloneDX/cyclonedx-ruby-gem, as Cocoapods was inspired by Gem.

**Comment by damienb** [comment]
Hello,
Is there anything functional so far for cocoapods?
Have a good day

**Comment by stevespringett** [comment]
Not yet. There's a help wanted statement on the projects readme.

**Comment by jgongo** [comment]
Hi! Is there anybody working on this? I could devote time to this if you point me to some guidelines/documentation...

**Comment by damienb** [comment]
Hello,
I share with you a very minimalist little script that allows you to browse the PodFile file and output a bom.xml file with the minimum required.
The method is certainly not the best but it allows to have a first result.
Have a good day
[podToBom.sh.zip](https://github.com/CycloneDX/cyclonedx-cocoapods/files/6211862/podToBom.sh.zip)

**Comment by jgongo** [comment]
@stevespringett can you please take a look at #2 ?

I have just noticed I didn't modify the README file, so I'll do it and add it
