### ISSUE TITLE
Cyclonedx-cocoapods command dosen't work after installing all gems from source

### ISSUE THREAD

**Issue by Masireddy65** [CycloneDX/cyclonedx-cocoapods#19]
I have installed Cyclonedx-cocoapods on mac from source

Done installing documentation for ffi, ethon, typhoeus, netrc, public_suffix, addressable, cocoapods-core, claide, cocoapods-deintegrate, cocoapods-downloader, cocoapods-plugins, cocoapods-search, cocoapods-trunk, cocoapods-try, molinillo, atomos, rexml, CFPropertyList, colored2, nanaimo, xcodeproj, escape, fourflusher, gh_inspector, ruby-macho, cocoapods, cyclonedx-cocoapods after 10 seconds 

27 gems installed 

But receiving command not found error while trying cyclonedx-cocoapods --path --output
ZSH: command not found: cyclonedx-cocoapods

Any help appreciable. thanks!

**Comment by YevhenPryliepov** [comment]
@jgongo @stevespringett any updates?

**Comment by nikekannan** [comment]
Facing same issue

**Comment by gowthamrajc** [comment]
Same issue for me, couldn't able to cyclonedx-cocoapods for my project. Some help is appreciated.

**Comment by macblazer** [comment]
I cloned the source from Github, then with Terminal open to that source code directory ran `gem build cyclonedx-cocoapods.gemspec` and `gem install cyclonedx-cocoapods-0.1.1.gem`.  After both commands completed successfully, then I have had success running `cyclonedx-cocoapods` from my project directories.

I am using `rbenv` to manage my ruby environment, and have ruby 3.0.3 currently.

**Comment by gowthamrajc** [comment]
We tried the same using ruby 3.0.3 using rbenv, but the gem installation results in empty directory for cyclonedx-cocoapods-0.1.1. Attached the screenshot for your reference: 
<img width="1787" alt="Screenshot 2022-01-05 at 12 40 57 PM" src="https://user-images.githubusercontent.com/7124019/148175581-490e2eba-09ff-4778-8113-f0a03c7aa757.png">
 
@macblazer  Can you share the screenshot of the gem directory for cyclonedx-cocoapods-0.1.1 after installation?

**Comment by macblazer** [comment]
There is the expected copy of the gem files there.
 
<img width="992" alt="cyclonedx-cocoapods install" src="https://user-images.githubusercontent.com/6825873/148291781-40c8f577-7810-451e-8fea-070f8283ca77.png">

Also, Terminal shows this:
```
$ which cyclonedx-cocoapods
/Users/kyle.hammond/.rbenv/shims/cyclonedx-cocoapods
```

Not sure if this is required or has anything to do with the problem, but I have this in my `.zshrc` file to set up rbenv when Terminal launches:

```
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
```

**Comment by nikekannan** [comment]
Would you mind sharing the content of the cyclonedx-cocoapods-0.1.1.  Not really sure what we are doing wrong here.

**Comment by gowthamrajc** [comment]
@macblazer Thanks for sharing the screenshot. I'm not sure what i'm doing wrong here. I again cloned the latest source from Github and did the exact steps to build and install it, but still no luck. I have attached the screenshot for the process: 
<img width="879" alt="Screenshot 2022-01-06 at 8 16 41 PM" src="https://user-images.githubusercontent.com/7124019/148401244-e8c00f44-93c7-485f-8a5a-5e34d3789f5b.png">

I don't know why i'm getting some error here:
**fatal: not a git repository (or any of the parent directories): .git
WARNING:  no files specified
WARNING:  See https://guides.rubygems.org/specification-reference/ for help**

Meanwhile did you changed anything in the source file or gemspec before building & installing this gem?

**Comment by macblazer** [comment]
The gemspec file uses `git ls-files ...` to determine which files should be in the installed gem.  Without the `.git` folder this doesn't work.  There are alternatives to using `git` shown on the [Ruby Gems spec reference](https://guides.rubygems.org/specification-reference/#files).

Did you clone the code or download/copy it?  This workflow is fine:

```
$ git clone git@github.com:CycloneDX/cyclonedx-cocoapods.git
Cloning into 'cyclonedx-cocoapods'...
remote: Enumerating objects: 668, done.
remote: Counting objects: 100% (668/668), done.
remote: Compressing objects: 100% (273/273), done.
remote: Total 668 (delta 326), reused 575 (delta 249), pack-reused 0
Receiving objects: 100% (668/668), 111.42 KiB | 1.05 MiB/s, done.
Resolving deltas: 100% (326/326), done.

$ cd cyclonedx-cocoapods 

$ gem build cyclonedx-cocoapods.gemspec 
  Successfully built RubyGem
  Name: cyclonedx-cocoapods
  Version: 0.1.1
  File: cyclonedx-cocoapods-0.1.1.gem

$ gem install cyclonedx-cocoapods-0.1.1.gem 
Successfully installed cyclonedx-cocoapods-0.1.1
Parsing documentation for cyclonedx-cocoapods-0.1.1
Done installing documentation for cyclonedx-cocoapods after 0 seconds
1 gem installed

$ ls ~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/cyclonedx-cocoapods-0.1.1 
Gemfile       LICENSE       README.md     bin       exe
Gemfile.lock      NOTICE        Rakefile      cyclonedx-cocoapods.gemspec lib

$
```

However, if I do this (removing the `.git` folder) I get the results you've reported:

```
$ git clone git@github.com:CycloneDX/cyclonedx-cocoapods.git
Cloning into 'cyclonedx-cocoapods'...
remote: Enumerating objects: 668, done.
remote: Counting objects: 100% (668/668), done.
remote: Compressing objects: 100% (273/273), done.
remote: Total 668 (delta 326), reused 575 (delta 249), pack-reused 0
Receiving objects: 100% (668/668), 111.42 KiB | 1.28 MiB/s, done.
Resolving deltas: 100% (326/326), done.

$ cd cyclonedx-cocoapods 

$ sudo rm -R .git

$ gem build cyclonedx-cocoapods.gemspec              
fatal: not a git repository (or any of the parent directories): .git
WARNING:  no files specified
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: cyclonedx-cocoapods
  Version: 0.1.1
  File: cyclonedx-cocoapods-0.1.1.gem

$ gem install cyclonedx-cocoapods-0.1.1.gem            
Successfully installed cyclonedx-cocoapods-0.1.1
Parsing documentation for cyclonedx-cocoapods-0.1.1
Done installing documentation for cyclonedx-cocoapods after 0 seconds
1 gem installed

$ ls ~/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0/gems/cyclonedx-cocoapods-0.1.1

$
```

**Comment by macblazer** [comment]
The `cyclonedx-cocoapods.gemspec` should probably be adjusted to use this for the `.files` line.  When a CHANGELOG.md file is added, that is also typically added to the release files list.

```
  spec.files = Dir["lib/**/*.{rb,json}"] + %w{ exe/cyclonedx-cocoapods README.md LICENSE NOTICE }
```

**Comment by nikekannan** [comment]
Thanks a ton @macblazer 👍  Your approach really works for us to get the BOM file.

**Comment by coderpatros** [comment]
Thanks to everyone involved in this thread. Apologies someone hasn't been onto this. We've all been really busy and those that have had time aren't familiar enough with the ecosystem. Is anyone able to raise a PR to resolve this issue?

**Comment by macblazer** [comment]
I can make a PR.  I didn't have time yesterday, but I will get on it today.

**Comment by ebubekiracar** [comment]
> @macblazer Thanks for sharing the screenshot. I'm not sure what i'm doing wrong here. I again cloned the latest source from Github and did the exact steps to build and install it, but still no luck. I have attached the screenshot for the process: <img alt="Screenshot 2022-01-06 at 8 16 41 PM" width="879" src="https://user-images.githubusercontent.com/7124019/148401244-e8c00f44-93c7-485f-8a5a-5e34d3789f5b.png">
> 
> I don't know why i'm getting some error here: **fatal: not a git repository (or any of the parent directories): .git WARNING: no files specified WARNING: See https://guides.rubygems.org/specification-reference/ for help**
> 
> Meanwhile did you changed anything in the source file or gemspec before building & installing this gem?


Make sure you add all files to git. If you use this command` git add --all` the problem will be solved
