### ISSUE TITLE
Add repository_url to purl for internal pods

### ISSUE THREAD

**Issue by macblazer** [CycloneDX/cyclonedx-cocoapods#3]
To better identify internally developed and hosted CocoaPods, the `purl` element should have a `repository_url` parameter added to it when the pod is not from the main CocoaPods git repo or CDN.

`repository_url` is explained with a couple examples on this page: https://github.com/package-url/purl-spec

The main CocoaPods repositories are `https://github.com/CocoaPods/Specs.git` and `https://cdn.cocoapods.org/`.

**Comment by stevespringett** [comment]
Related to https://github.com/package-url/purl-spec/issues/103
