### ISSUE TITLE
Error after update to latest rubygems version "Version 5.6.2 not found for pod Alamofire"

### ISSUE THREAD

**Issue by chuchivic** [CycloneDX/cyclonedx-cocoapods#47]
Worked fine before update the gemfile.lock, but after a bundle update I'm getting this error:

`+ cyclonedx-cocoapods --path . --output ./bom.xml`

`
E, [2022-10-05T11:51:12.904570 #78143] ERROR -- : Version 5.6.2 not found for pod Alamofire
/Users/jenkins/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cyclonedx-cocoapods-1.1.0/lib/cyclonedx/cocoapods/pod_attributes.rb:40:in `attributes_for'
/Users/jenkins/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cyclonedx-cocoapods-1.1.0/lib/cyclonedx/cocoapods/pod_attributes.rb:68:in `complete_information_from_source'
/Users/jenkins/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cyclonedx-cocoapods-1.1.0/lib/cyclonedx/cocoapods/podfile_analyzer.rb:67:in `block in populate_pods_with_additional_info'
/Users/jenkins/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cyclonedx-cocoapods-1.1.0/lib/cyclonedx/cocoapods/podfile_analyzer.rb:65:in `each'
/Users/jenkins/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cyclonedx-cocoapods-1.1.0/lib/cyclonedx/cocoapods/podfile_analyzer.rb:65:in `populate_pods_with_additional_info'
/Users/jenkins/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cyclonedx-cocoapods-1.1.0/lib/cyclonedx/cocoapods/cli_runner.rb:43:in `run'
/Users/jenkins/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cyclonedx-cocoapods-1.1.0/exe/cyclonedx-cocoapods:23:in `<top (required)>'
/Users/jenkins/.rbenv/versions/2.7.6/bin/cyclonedx-cocoapods:23:in `load'
/Users/jenkins/.rbenv/versions/2.7.6/bin/cyclonedx-cocoapods:23:in `<main>'`

**Comment by macblazer** [comment]
v5.6.2 is the current version of Alamofire.  It's likely that on the computer where you ran this command you will need to do a `pod repo update` to get the local computer cache of pods up to date.

**Comment by chuchivic** [comment]
yep, that's the issue and the solution, very thanks @macblazer !
