### ISSUE TITLE
Update compatibility with newer CocoaPod-versions

### ISSUE THREAD

**Issue by malice00** [CycloneDX/cyclonedx-cocoapods#51]
Would it be possible to update the dependency to cocoapods to a newer/the latest version?

We are using 1.11.3 for our builds, but to run this tool I have to use a second installation of Ruby with a lesser CocoaPods version. Seeing how I already built my project with the newer version and this tool actually runs and doesn't (seem) to change anything in my workspace, I assume there is no real reason to have it pinned to an older version.

**Comment by macblazer** [comment]
That makes sense.  I'll take a look at Ruby's gemspec specification for versioning and probably pin the cocoapods dependency to a minimum of what we have now but still less than v2 (if there ever is one of those).

In the meantime, you can use bundler to ensure you've got a stable set of dependencies for the tools needed.

Alternatively, you might be able to just install the specific version of cocoapods with something like:

`gem install cocoapods:1.10.1`

**Comment by malice00** [comment]
I tried with bundler, but when I tell it to use CocoaPods 1.11.3 and cyclonedx-cocoapods, it refuses to install. The problem is that 1.11.3 has some changes that we needed after the update to XCode 12 or 13...

Thanks for the fast PR, I'll give it a try when it's released! (Don't know enough about Ruby to build my own, I'm afraid...)
