### ISSUE TITLE
SBOM generation is taking extremely long

### ISSUE THREAD

**Issue by malice00** [CycloneDX/cyclonedx-cocoapods#78]
We noticed that building our projects and generating SBOMs on our CI was taking very long. A little analysis showed us that one of the reasons for this is that cyclonedx-cocoapods is taking (in some cases) almost 2 hours to generate an SBOM!
Seeing how very often the problem at work is our company using a proxy, in this case I was able to reproduce the problem at home as well, where I do not have a proxy.

When generating an SBOM for [this project](https://github.com/malice00/cdxgen-expo-test) (Branch 'ios'), I was able to reproduce the SBOM generation taking over 3 hours on my M3 Pro MacBook w/ 8GB of RAM. It also hit a maximum of 30GB memory consumption -- which probably didn't help the speed as that means the machine was using a lot of swap... On one of the work projects (which I understandably can't share), I even hit more than 30GB of memory usage.
Unfortunately I don't have memory usage data from the server at work, but I can tell you it has 32GBs of RAM, so that should be less of a problem than at home. It does however have a slower CPU (still an intel), but judging from my testing cyclonedx-cocoapods is using more memory than it is using the CPU.

Could you please have a look at why it takes so long to generate an SBOM? Having our builds take over 2 hours is ruining the idea of CI/CD.

Here's a part of the logs -- I ran verbose output, but that didn't help much:

```
time cyclonedx-cocoapods -o bom.xml -n cdxg -v 1.0.0 -t application --verbose
D, [2024-11-09T20:54:57.312521 #53120] DEBUG -- : Running cyclonedx-cocoapods with options: {:bom_file_path=>"bom.xml", :name=>"EIP", :version=>"1.0.0", :type=>"application", :verbose=>true}
... <Output from EXPO> ...
D, [2024-11-09T20:55:02.660440 #53120] DEBUG -- : Parsing pods from /Users/malice/workspace/cdxgen-expo-test/ios/Podfile
D, [2024-11-09T20:55:02.660871 #53120] DEBUG -- : Including all pods for targets: ["Pods", "Pods-cdxgenexpotest"]
D, [2024-11-10T00:08:37.400936 #53120] DEBUG -- : Parsing sources from /Users/malice/workspace/cdxgen-expo-test/ios/Podfile
D, [2024-11-10T00:08:37.403183 #53120] DEBUG -- : Source manager successfully created with all needed sources
D, [2024-11-10T00:09:19.049786 #53120] DEBUG -- : Completing information for boost
... <More dependencies> ...
D, [2024-11-10T00:09:20.120928 #53120] DEBUG -- : Including all pods for targets: ["Pods", "Pods-cdxgenexpotest"]
I, [2024-11-10T00:09:20.149754 #53120]  INFO -- : BOM written to /Users/malice/workspace/cdxgen-expo-test/ios/bom.xml
cyclonedx-cocoapods -o bom.xml -n EIP -v 1.0.0 -t application --verbose  3273.60s user 1535.56s system 41% cpu 3:14:23.29 total
```

To run the test-project, use at least NodeJS v18.18.0 and CocoaPods 1.14.3:
```
npm ci --legacy-peer-deps
cd ios
pod install
cyclonedx-cocoapods -o bom.xml -n cdxg -v 1.0.0 -t application --verbose
```

**Comment by macblazer** [comment]
I can definitely look into it.

The Podfile.lock shows that the project has about 100 unique dependencies which is definitely a higher number than I've tested with, but it shouldn't take 3+ hours and tens of gigabytes of memory.

I haven't done anything with Ruby profiling and optimizations, so looking forward to some reading and learning new tools.  👍

**Comment by macblazer** [comment]
@malice00 There was some hideously non-performant code that I wrote to run through all the pods used in the particular targets being analyzed in order to gather them into a simple list of names along with a list of their direct dependencies.  It worked well enough for five or ten pods, but when there are hundreds of pods it was...._bad_.  I didn't really dig into the exact level of bad, but approximately `O(n^3)` kind of badness.

This PR simplifies that code a bit, and makes it go **a lot** faster.  This is the output on my M3 iMac.

```bash
$ time cyclonedx-cocoapods -o bom.xml -n cdxg -v 1.0.0 -t application --verbose
...[all the debug output]...
cyclonedx-cocoapods -o bom.xml -n cdxg -v 1.0.0 -t application --verbose  4.80s user 0.82s system 85% cpu 6.584 total
```

About five seconds total.  Like I said, the original code there was hideously non-performant.

Look for the new version to be released soon.

**Comment by malice00** [comment]
I tried your branch and am (locally) also down to around 5 seconds! Huge gain, thank you so much!
