### ISSUE TITLE
Failing on local pod specs

### ISSUE THREAD

**Issue by barnaclebarnes** [CycloneDX/cyclonedx-cocoapods#9]
I'm getting an error `[!] Unable to find a pod with name matching `^BNFMatomo$'`

My `Podfile.lock` has the following lines (showing only those relevant to the Pod)

```
PODS:
  - BNFMatomo (0.1.2)

DEPENDENCIES:
  - BNFMatomo (from `../node_modules/react-native-matomo`)

EXTERNAL SOURCES:
  BNFMatomo:
    :path: "../node_modules/react-native-matomo"
```

Any ideas how to make sure it deals with Pods not in the main CocoaPods search?

**Comment by jgongo** [comment]
@barnaclebarnes can you please check if the code in #10 solves your issue? Thanks!

**Comment by barnaclebarnes** [comment]
@jgongo I'm having trouble testing this. This is what I'm getting:

```
➜  BUNDLE_GEMFILE=~/Documents/cyclonedx-cocoapods/Gemfile be ~/Documents/cyclonedx-cocoapods/exe/cyclonedx-cocoapods --verbose -p ~/Documents/mytours-rn/ios -o ./bom.xml
D, [2021-05-25T11:04:01.063166 #44091] DEBUG -- : Running cyclonedx-cocoapods with options: {:verbose=>true, :path=>"/Users/barnaclebarnes/Documents/mytours-rn/ios", :bom_file_path=>"./bom.xml"}
E, [2021-05-25T11:04:01.136499 #44091] ERROR -- :
[!] Invalid `Podfile` file: [!] /Users/barnaclebarnes/.nvm/versions/node/v12.16.3/bin/node -e try {console.log(require('@react-native-community/cli').bin);} catch (e) {console.log(require('react-native/cli').bin);}

internal/modules/cjs/loader.js:960
  throw err;
  ^

Error: Cannot find module 'react-native/cli'
Require stack:
- /Users/barnaclebarnes/Documents/mytours-web/[eval]
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at [eval]:1:87
    at Script.runInThisContext (vm.js:120:20)
    at Object.runInThisContext (vm.js:311:38)
    at Object.<anonymous> ([eval]-wrapper:10:26)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at evalScript (internal/process/execution.js:94:25) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/Users/barnaclebarnes/Documents/mytours-web/[eval]' ]
}
.

 #  from /Users/barnaclebarnes/Documents/mytours-rn/ios/Podfile:79
 #  -------------------------------------------
 #
 >    use_native_modules!
 #  end
 #  -------------------------------------------
```

I can't add it as a dependency to my app as you have locked CocoaPods and nokogiri to older versions.

Any suggestions?

**Comment by jgongo** [comment]
@barnaclebarnes 🤔 I don't understand this error... It seems the `Podfile` loading is failing due to some error with `react-native/cli` but I'm not sure this is `cyclonedx-cocoapods`'s fault. I guess you are working in a React Native project...

Does `pod install` work properly? A quick googling of the error led me to this [StackOverflow discussion](https://stackoverflow.com/questions/56917963/react-native-ios-podfile-issue-with-use-native-modules). Can you please double check there's no problem with your project? If your project is functioning properly, can you please provide a minimal test case causing this error?

I neither understand this:

> I can't add it as a dependency to my app as you have locked CocoaPods and nokogiri to older versions.

What do you mean? What do the versions of the dependencies of `cyclonedx-cocoapods` have to do with the dependencies in your app? They should be independent of each other.

**Comment by barnaclebarnes** [comment]
@jgongo Completely my fault. I didn't have some project dependencies installed which was throwing up those errors. I managed to successfully create the BOM. 

I guess the next things is to pull through the license and other info through for the local Pods? For example here is what is output for one of the packages:

```
<component type="library">
      <name>FBLazyVector</name>
      <version>0.61.5</version>
      <hashes>
        <hash alg="SHA-1">aaeaf388755e4f29cd74acbc9e3b8da6d807c37f</hash>
      </hashes>
      <purl>pkg:cocoapods/FBLazyVector@0.61.5</purl>
    </component>
```

But the PodSpec has this in it:

```
Pod::Spec.new do |s|
  s.name                   = "FBLazyVector"
  s.version                = version
  s.summary                = "-"  # TODO
  s.homepage               = "http://facebook.github.io/react-native/"
  s.license                = package["license"]
  s.author                 = "Facebook, Inc. and its affiliates"
  s.platforms              = { :ios => "9.0", :tvos => "9.2" }
  s.source                 = source
  s.source_files           = "**/*.{c,h,m,mm,cpp}"
  s.header_dir             = "FBLazyVector"
end
```

Thanks for getting that main generation fixed up so quickly.

**Comment by jgongo** [comment]
> @jgongo Completely my fault. 

No worries 😊 

> I guess the next things is to pull through the license and other info through for the local Pods?

Yes, I have created #11 for that, I'll take a look at it when I have some time.

> Thanks for getting that main generation fixed up so quickly.

You're welcome 😊
